### PR TITLE
Switch to Symusic

### PR DESCRIPTION
**Pull request by Natooz**
Following #112, this PR switches the MIDI load/write backend from [miditoolkit](https://github.com/YatingMusic/miditoolkit) to [symusic](https://github.com/Yikai-Liao/symusic).

@Yikai-Liao @lzqlzzq

### CODE REVIEW

**Comment by Natooz** [comment]
@Yikai-Liao things are moving, the test for one-track tok-detok are all passing!
Next step is multitrack, which should hopefully be quick. Then methods and misc. And I'll finish with the BPE which requires a few code modifications.

When everything is done on the MidiTok side, I'll try to contribute to symusic by adding a few tests on the CI pipeline, to ensure the robustness of the parsing/dumping processes.

**Comment by Natooz** [comment]
@Yikai-Liao we are almost done here!
There is still one small issue regarding the tempos, I'm not sur how the `Tempo()` should be created since the last update. It seems that the second positional argument initialises the MIDI int value for both the `.qpm` and `.tempo` attributes.

Capture d’écran 2023-12-22 à 18 00 50

Hopefully when this is resolved we will be ready to review and merge!
This will mark the V3.0.0 of MidiTok (I'll still have a few things to do/fix before releasing it).
I'll run tokenization benchmarks in order to mesure the speed gains of the new version!

**Comment by Yikai-Liao** [comment]
> @Yikai-Liao we are almost done here!
> There is still one small issue regarding the tempos, I'm not sur how the `Tempo()` should be created since the last update. It seems that the second positional argument initialises the MIDI int value for both the `.qpm` and `.tempo` attributes.
> 
> Capture d’écran 2023-12-22 à 18 00 50
> 
> Hopefully when this is resolved we will be ready to review and merge!
> This will mark the V3.0.0 of MidiTok (I'll still have a few things to do/fix before releasing it).
> I'll run tokenization benchmarks in order to mesure the speed gains of the new version!

Oh, I forget to change the tempo factory.  I add qpm is to make it more clear that this property refers to quarters per minute， But I'm still not sure, should I use this abbreviation?

For the tempo factory, I think users should be able to choose one of  These two arguments(microseconds per quarter and  quarters per minute)  as the argument of the constructor.  Because in some kind of situations, we could just use qpm  for convenience,  but in other cases, we might need to avoid any precision loss by passing a int.

Two possible signatures might be
```python
__call__(self, time, qpm=None, mspq=None)
# or
__call__(self, time, quarter_per_min=None, ms_per_quarter=None)
```
I'm not sure which one is better for users.

**Comment by Natooz** [comment]
I agree with you for letting the choice to the user.
I don't have strong opinions on the arguments names. Maybe the second proposition follows more common practices?

**Comment by Yikai-Liao** [comment]
@Natooz TempoFactory have been fixed Yikai-Liao/symusic#14

**Comment by Natooz** [comment]
Thank you!
I just tested it by installing from source, it should be good!
I still needed to manually check the tempos by rounding the qpm and mspq values instead of using the built-in `__eq__` method, but that's ok as some info is lost with the conversions and there is nothing we can do about it.
When do you plan to release the next version?

**Comment by Yikai-Liao** [comment]
> Thank you!
> I just tested it by installing from source, it should be good!
> I still needed to manually check the tempos by rounding the qpm and mspq values instead of using the built-in `__eq__` method, but that's ok as some info is lost with the conversions and there is nothing we can do about it.
> When do you plan to release the next version?

I only store mspq(int) in the struct.  So I think currently there is no Information loss.  So why do you need to define a custom __eq__ function?

**Comment by Natooz** [comment]
That's because here in MidiTok we use the qpm information, which is rounded to 2 decimals. Hence we lose a bit of accuracy, which we must take into account during the tests.

**Comment by Natooz** [comment]
# Benchmark MIDI preprocessing

Benchmark on the `preprocess_midi` method which is called before tokenizing a MIDI in order to resample / filter its contents.

## Code

```Python
#!/usr/bin/python3 python

from copy import deepcopy
from pathlib import Path
from time import time
from typing import List

import numpy as np
from symusic import Score

import miditok


TOKENIZER_CONFIG_KWARGS = {
    "use_chords": False,  # set false to speed up tests
    "use_rests": True,
    "use_tempos": True,
    "use_time_signatures": True,
    "use_sustain_pedals": True,
    "use_pitch_bends": True,
    "use_pitch_intervals": True,
    "log_tempos": True,
    "beat_res": {(0, 4): 8, (4, 12): 4, (12, 16): 2},
    "beat_res_rest": {(0, 2): 4, (2, 12): 2},
    "delete_equal_successive_time_sig_changes": True,
    "delete_equal_successive_tempo_changes": True,
}

HERE = Path(__file__).parent
MIDI_PATHS_ONE_TRACK = sorted((HERE / "MIDIs_one_track").rglob("*.mid"))
MIDI_PATHS_MULTITRACK = sorted((HERE / "MIDIs_multitrack").rglob("*.mid"))
MIDI_PATHS_ALL = sorted(
    deepcopy(MIDI_PATHS_ONE_TRACK) + deepcopy(MIDI_PATHS_MULTITRACK)
)
TOKENIZATIONS = ["Structured", "REMI", "MIDILike", "TSD"]


def benchmark_preprocess(midi_paths: List[Path]):
    r"""Reads MIDI files and call `tokenizer.preprocess_midi` on them.

    :param midi_paths: list of paths to MIDI files.
    """
    for tokenization in TOKENIZATIONS:
        tok_config = miditok.TokenizerConfig(**TOKENIZER_CONFIG_KWARGS)
        tokenizer = getattr(miditok, tokenization)(tok_config)
        times = []
        for midi_path in midi_paths:
            midi = Score(midi_path)
            t0 = time()
            tokenizer.preprocess_midi(midi)
            t1 = time() - t0
            times.append(t1)

        times = np.array(times)
        mean = np.mean(times)
        std = np.std(times)
        print(f"{tokenization}: {mean:.3f} ± {std:.3f} sec")


if __name__ == "__main__":
    benchmark_preprocess(MIDI_PATHS_ALL)
```

## Results

### Aligning times to a "grid" (old method before 0a0390dd055f9ac30e1ee89c9451130880eed7f4)

```
Structured: 0.403 ± 0.388 sec
REMI: 0.407 ± 0.393 sec
MIDILike: 0.408 ± 0.396 sec
TSD: 0.417 ± 0.392 sec
```

### Resampling the time division with numpy

#### eeeb65bdd10ea71756514891cfe53a0c95490d6f

Here MIDILike also calls `fix_offsets_overlapping_notes()` on all tracks

```
Structured: 0.321 ± 0.320 sec
REMI: 0.347 ± 0.349 sec
MIDILike: 0.477 ± 0.471 sec
TSD: 0.347 ± 0.349 sec
```

#### d1b95639b701e17047c5b44538417ba24c1f3064

```
Structured: 0.345 ± 0.354 sec
REMI: 0.402 ± 0.409 sec
MIDILike: 0.493 ± 0.483 sec
TSD: 0.340 ± 0.336 sec
```

### Resampling with symusic's `score.resample(new_tpq)` method

WIP before committing changes

```
Structured: 0.279 ± 0.282 sec
REMI: 0.280 ± 0.288 sec
MIDILike: 0.441 ± 0.454 sec
TSD: 0.300 ± 0.302 sec
```

**Comment by Natooz** [comment]
## Note sorting benchmark

### `track.notes.sort(key=lambda x: (x.start, x.pitch, x.end))`

```
Structured: 0.191 ± 0.228 sec
REMI: 0.194 ± 0.235 sec
MIDILike: 0.217 ± 0.274 sec
TSD: 0.189 ± 0.223 sec
```

### `track.notes.sort(key=lambda (x.start, x.end))`

```
Structured: 0.136 ± 0.176 sec
REMI: 0.133 ± 0.171 sec
MIDILike: 0.137 ± 0.178 sec
TSD: 0.137 ± 0.179 sec
```

### `track.notes.sort(key=lambda x: x.start)`

```
Structured: 0.111 ± 0.147 sec
REMI: 0.103 ± 0.135 sec
MIDILike: 0.107 ± 0.134 sec
TSD: 0.112 ± 0.139 sec
```

**Comment by Natooz** [comment]
@Yikai-Liao Thank you for your reactivity in releasing the latest version with the resampling feature! 🫶
I have been adapting the MIDI preprocessing to use it, as it is much faster than the numpy alternative.
I'm currently working on making the preprocessing faster. It turns out most of the time is spent on sorting the notes. I'm currently working on reducing the calls to sorting.

I wanted to ask you, when loading the MIDI, does symusic sorts the tempo, time signatures and other MIDI events? I ran some tests and they appear to be sorted, but I wanted to be sure.
And if that's the case, do you think sorting the track events (notes, controls, pitch bends) is something that could also be done? This could be left to the user's preference as it would increase the object creation time, by providing an argument when creating the `Score` (set to False by default?).

Lastly, one test case is failing here on Windows. It's an iostream error occurring when loading a MIDI that has been augmented (pitch and other attributes shifted) and dumped. I didn't dig into it yet, but as it's only happening on Windows it could be an error related to symusic. Do you have a clue on what it could be? I can test it myself on windows, maybe in a few days after clearing more important stuff.

I'll add in MidiTok's backlog passing the preprocessing, and maybe even more steps in the tokenization workflow, in c++ with pybind.

**Comment by Yikai-Liao** [comment]
symusic do sort all score events (because there is no guarantee for their original order in midi).

However, for track events, their order is fixed:

* notes and pedal follows the order of note off events. May be I should sort it by `(time, duration)`?
* other events follows the order of original events, which should be the time order (I haven't tested it).

All the sort methods in symusic use `time` as the default key, while using python lambda function will introduce a large overhead. So you will see that, `track.notes.sort(key=lambda x: x.start)` would be much slower than `track.notes.sort()`

BTW, `track.sort()` is also implemented. But you can't specify a key function because it have to deal with all kinds of events. 

If the situation is limited, maybe we could add the specific key used in sort into symusic.

**Comment by Natooz** [comment]
Thank you for the clarifications!

Is there a reason to sort notes and pedals by end value?
Having the possibility to specify the keys directly in symusic would greatly reduce the overall tokenization time. But I don't want to ask more "secondary" features for symusic that would take some of your time again, as you already did so much.

**Comment by Yikai-Liao** [comment]
The reason is that `Note` is created when they are moved out of the `last_note_on` queue. And I just don't sort them. Its reasonable to sort them, may be by (start, duration) ?

if we only need to sort by attributes, we could directly generate (by macro ) $A_4^4 + A_4^3 + A_4^2 + A_4^1 = 24 + 24 + 12 + 4 = 64$ key functions. although it is quite stupid.

**Comment by Natooz** [comment]
### Preprocessing results from 56fdaef4fb9a8d29533bf250a7f6c458cc1d545b

```
Structured: 0.162 ± 0.173 sec
REMI: 0.172 ± 0.184 sec
MIDILike: 0.302 ± 0.323 sec
TSD: 0.174 ± 0.183 sec
```

Here the durations (of notes and pedals) are also preprocessed, by being aligned to the values of the tokenizer's vocabulary (except for MIDILike which is not concerned).
Sorting is done only by `start` by default, + `pitch` if using pitch intervals, + `duration` and `velocity` if using NoteOn/NoteOff tokens (MIDILike).

**Comment by Yikai-Liao** [comment]
I have added sort for note and pedal while parsing midi. And the default sort key for NoteList and PedalList are changed to (time, pitch, duration) and (time, duration).

The new wheels (0.2.4) are building now.

**Comment by Natooz** [comment]
Wonderful!
Thank you, I'm testing it right away!

**Comment by Natooz** [comment]
@Yikai-Liao this is great!
The times of loading the MIDI + preprocessing is now on par with the last results measuring only the preprocessing without note sorting!

```
Structured: 0.071 ± 0.058 sec
REMI: 0.075 ± 0.063 sec
MIDILike: 0.062 ± 0.051 sec
TSD: 0.076 ± 0.062 sec
```

Thank you once again for your reactivity!

Concerning this PR, the switch is almost done, there is only this issue on Windows that I'll be fixing soon. When this is done, I think we will be reading to merge this (enormous) PR.
I added a few todos along the way, that should be done before releasing the v3.0.0. I'll still have some work to do, especially on the docs.

**Comment by Yikai-Liao** [comment]
utf8 file path support on Windows is added in librarify branch which will be merged to the main branch soon.

**Comment by Natooz** [comment]
@Yikai-Liao The bug happening on Windows was due to the § character in the file name of the MIDI being dumped. In MidiTok, this is done in the data augmentation method to tag the augmentation information in the file name.

It turns out that symusic raises an iostream error when trying to load a file with this character in the name.
Dumping a MIDI with § in the file name works, however the final file name ended altered (for example `Aicha§v-4.mid` to `AichaÂ§v-4.mid` in the example for the action here). I suspect this comes from an encoding error, § being not supported by the backend being used on Windows.

I simply switch from `§` to `#` in MidiTok, which solves the issue. Using § was purely arbitrary, I chose it as it is a character rarely used.
Anyway, I thought you might want to know this to try to make it work on all platforms. :)

I only have one task left before merging this PR! 🙌
And a few others after this before releasing the v3.0.0 hopefully in one or two weeks.

**Comment by Natooz** [comment]
I see our minds were synced here 🥲
I don't even have the time to report errors before you fix them 😄

**Comment by Natooz** [comment]
@Yikai-Liao @lzqlzzq
After extensive tests of almost all the codebase, I think the integration of symusic is finally done and well done. :)
We are good to merge this PR now, marking a nice way to end the year! 🙌
Thank you again for all your work and this great collaboration. 🫶 I truly believe symusic and minimidi are marking a big step in the community.

There are still some bugs and improvements that I want to do/fix before releasing the next release (v3.0.0). You'll be noticed when the changes will come.
Also, when the v3 will be released, as we can expect more people to use symusic, we can expect them to encounter some bugs. If that's the case, I'll keep you updated. Hopefully this should make the library even more robust and rich in features!

**Pull request merged**
