### PR TITLE
Changing the time division logic to ticks per quarter

### PR DESCRIPTION
**Pull request by Natooz**
Until now, we considered the time division to be expressed in ticks per beat for time calculations, except "bar-based" in tokenizer.
In the MIDI norm, the time division is however expressed in ticks per quarter, making our logic incorrect when the current time signature denominator is something other than 4 (quarter).

This PR fixes this issue by replacing the time calculations with the correct unit in mind, following the time signatures of a MIDI.

**Note:** when `config.use_time_signature` is `False`, we consider the time signature of the whole MIDI as 4/4. This doesn't affect the integrity of the MIDI content, as the decoded times will be identical, however the time signature information will not be taken into consideration.

### CODE REVIEW

**Comment by Natooz** [comment]
Tests are passing with time signature disabled.
To make them pass with different time signatures (and different ticks/beat values), we must resample the MIDI with a fixed ticks/beat value (i.e. different ticks/quarter values) depending on the time signatures.

Related: https://github.com/Yikai-Liao/symusic/issues/10

**Comment by Natooz** [comment]
Hi @Yikai-Liao 👋
I have been adapting the MIDI preprocessing steps with the new SOA interfaces, everything is great so far!
Only hiccup, I think some of the native methods (`sort`, `copy`) of most classes are broken with the new bindings. Here is the error when trying to sort a `NoteTickList` (`midi.tracks[0].notes.sort()`):

```
>       notes.sort()
E       TypeError: sort(): incompatible function arguments. The following argument types are supported:
E           1. sort(self, key: Optional[Callable[..., object]] = None, reverse: bool = False, inplace: bool = True) -> object
E       
E       Invoked with types: symusic.core.NoteTickList
```

When using `copy` (`copy(midi.time_signatures)`):

```
x = symusic.core.TimeSignatureTickList([TimeSignature(time=0, numerator=4, denominator=4)])
memo = None, func = <function __newobj__ at 0x10bdfb0d0>
args = (<class 'symusic.core.TimeSignatureTickList'>,)
state = b'\x01\x00\x00\x00\x00\x00\x00\x00\x04\x04\x00\x00', listiter = None
dictiter = None, deepcopy = <function deepcopy at 0x10be140d0>

    def _reconstruct(x, memo, func, args,
                     state=None, listiter=None, dictiter=None,
                     deepcopy=deepcopy):
        deep = memo is not None
        if deep and args:
            args = (deepcopy(arg, memo) for arg in args)
        y = func(*args)
        if deep:
            memo[id(x)] = y
    
        if state is not None:
            if deep:
                state = deepcopy(state, memo)
            if hasattr(y, '__setstate__'):
>               y.__setstate__(state)
E               TypeError: __setstate__(): incompatible function arguments. The following argument types are supported:
E                   1. __setstate__(self) -> symusic.core.TimeSignatureTickList
E               
E               Invoked with types: symusic.core.TimeSignatureTickList, bytes

/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py:272: TypeError
```

I haven't had time to dig further, I'll first fix the other preprocessing adaptations
(the test CI is broken on this PR)

**Comment by Yikai-Liao** [comment]
Things are fixed now. I got the type of argument key wrong. And I forgot to add a `__copy__` method for those List.
There is still one thing that we need to set a default key for sorting TrackList. What about (is_drum, program, name, note_num)

**Comment by Natooz** [comment]
Thank you for your reactivity!

The key order for sorting the tracks is I think well chosen.

> By the way, python 3.12 is not well supportted by nanobind now https://github.com/wjakob/nanobind/issues/397. There is a way to disable those warnings. But I'm not sure are there really some memory leak problems. The price for performance.

Thank you for the info! I'll keep an eye on this

**Comment by Yikai-Liao** [comment]
@Natooz New version is released

**Pull request merged**
